// scripts/gen-ai-map.ts — regenerate docs/ai/TREE.md (AI scaffolding map).
//
// "Generated scaffolding" for agents: a fresh, machine-generated snapshot of
// the source tree + package metadata, so AI agents always know where to look
// without guessing. Run after structural changes:
//
//   bun run gen:ai-map
//
// The curated, human-written map lives in docs/architecture.md; this file is
// the auto-updated companion (docs/ai/TREE.md).

import { readdirSync, statSync, writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = join(import.meta.dir, '..')

// Directories to snapshot (relative to repo root).
const SNAPSHOT_DIRS = ['src', 'rust', 'public', 'client', 'test', 'bench', 'scripts', 'examples', 'docs']

// Always skip (build output, vendored, VCS).
const SKIP = new Set([
  'node_modules',
  'target',
  'dist',
  'client-dist',
  'prebuilds',
  '.git',
  '.vscode',
])

function tree(dir: string, prefix = ''): string[] {
  const entries = readdirSync(dir)
    .filter((e) => !SKIP.has(e))
    .sort((a, b) => {
      const aDir = statSync(join(dir, a)).isDirectory()
      const bDir = statSync(join(dir, b)).isDirectory()
      if (aDir !== bDir) return aDir ? -1 : 1
      return a.localeCompare(b)
    })
  const lines: string[] = []
  entries.forEach((entry, i) => {
    const last = i === entries.length - 1
    const p = join(dir, entry)
    const isDir = statSync(p).isDirectory()
    lines.push(`${prefix}${last ? '└─' : '├─'} ${entry}${isDir ? '/' : ''}`)
    if (isDir) {
      lines.push(...tree(p, prefix + (last ? '   ' : '│  ')))
    }
  })
  return lines
}

function pkg(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
  } catch {
    return {}
  }
}

function cargoPackage(): Record<string, unknown> {
  const path = join(ROOT, 'rust/Cargo.toml')
  if (!existsSync(path)) return {}
  const raw = readFileSync(path, 'utf8')
  const m = raw.match(/\[package\]([\s\S]*?)(?=\n\[)/)
  const body = m?.[1] ?? ''
  const out: Record<string, string> = {}
  for (const line of body.split('\n')) {
    const kv = line.match(/^\s*([a-zA-Z0-9_-]+)\s*=\s*"([^"]+)"/)
    if (kv && kv[1] !== undefined && kv[2] !== undefined) out[kv[1]] = kv[2]
  }
  return out
}

function main(): void {
  const p = pkg()
  const cargo = cargoPackage()
  const lines: string[] = []
  lines.push('# TREE — generated scaffolding map')
  lines.push('')
  lines.push('> AUTO-GENERATED by `bun run gen:ai-map` (`scripts/gen-ai-map.ts`).')
  lines.push('> Do not edit by hand — regenerate after structural changes. The')
  lines.push('> curated maps live in `docs/architecture.md` + `docs/wire-format.md`')
  lines.push('> (and `AGENTS.md` for agents).')
  lines.push('')
  lines.push(`- package: \`${String(p.name ?? 'unknown')}\` v${String(p.version ?? '?')}`)
  if (p.engines) lines.push(`- engines: ${JSON.stringify(p.engines)}`)
  if (cargo.name) lines.push(`- rust crate: \`${cargo.name}\` v${String(cargo.version ?? '?')}`)
  const scripts = (p.scripts ?? {}) as Record<string, string>
  const scriptKeys = Object.keys(scripts)
  lines.push(`- scripts (${scriptKeys.length}): \`${scriptKeys.slice(0, 12).join('`, `')}\`${scriptKeys.length > 12 ? ', …' : ''}`)
  lines.push('')
  for (const dir of SNAPSHOT_DIRS) {
    const abs = join(ROOT, dir)
    if (!existsSync(abs)) continue
    lines.push(`## ${dir}/`)
    lines.push('')
    lines.push('```')
    lines.push(`${dir}/`)
    lines.push(...tree(abs))
    lines.push('```')
    lines.push('')
  }
  lines.push('## Notes')
  lines.push('')
  lines.push('- `SKIP` set in the script excludes build output (target/, dist/, client-dist/, prebuilds/, node_modules/).')
  lines.push('- `src/generated/`, `rust/src/generated/`, `rust/src/transcode/generated.rs` are regenerated by `bun run generate` — never hand-edit.')
  lines.push('')

  const outDir = join(ROOT, 'docs', 'ai')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'TREE.md'), lines.join('\n'))
  console.log(`✓ regenerated ${relative(ROOT, join(outDir, 'TREE.md'))} (${lines.length} lines)`)
}

main()
