/**
 * `bun run generate` — builds the whole wire stack from the TypeBox schemas.
 *
 *   1. TypeBox model → `src/generated/fbs/backend.fbs`
 *   2. `flatc --ts`  → `src/generated/ts/`      (browser + Bun decoders)
 *   3. `flatc --rust`→ `src/generated/rust/`    → copied into `rust/src/generated/backend.rs`
 *   4. Rust glue    → `rust/src/transcode/generated.rs`
 *   5. Registry     → `src/generated/registry.ts` (server + client event routing)
 *
 * Requires `flatc` on PATH (the FlatBuffers compiler). Keep the flatc binary
 * and the `flatbuffers` crate/npm versions aligned.
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { controlEvents, events, schemas } from "../src/schema/index";
import { emitDirectSer } from "./direct-gen";
import { emitRegistry } from "./registry-gen";
import { emitRustGlue } from "./rust-glue-gen";
import { buildModel } from "./schema-model";
import { emitFbs } from "./typebox-to-fbs";
import { eventId } from "./hash";
import { emitTsSer } from "./ts-ser-gen";
import { WIRE_VERSION } from "./constants";

const ROOT = join(import.meta.dir, "..");

function run(cmd: string, args: string[], cwd: string): void {
  const res = spawnSync(cmd, args, { cwd, encoding: "utf8" });
  if (res.status !== 0) {
    if (res.stdout) console.error(res.stdout);
    if (res.stderr) console.error(res.stderr);
    throw new Error(
      `command failed (${res.status}): ${cmd} ${args.join(" ")}\n` +
        `Is \`flatc\` installed? (brew install flatbuffers / apt install flatbuffers-compiler / download from https://flatbuffers.dev)`,
    );
  }
}

function main(): void {
  const model = buildModel(schemas as never, events as never, controlEvents as never);

  // Stable-hash collision check: every event must have a unique FNV-1a id.
  // (Astronomically unlikely for sane registries, but a hard fail beats a
  // silently ambiguous wire id.)
  const seen = new Map<number, string>();
  for (const ev of model.events) {
    const id = eventId(ev.name);
    const existing = seen.get(id);
    if (existing !== undefined) {
      throw new Error(`event id collision: "${ev.name}" and "${existing}" both hash to ${id} — rename one of them`);
    }
    seen.set(id, ev.name);
  }

  // 1. .fbs
  const fbsDir = join(ROOT, "src", "generated", "fbs");
  mkdirSync(fbsDir, { recursive: true });
  const fbsPath = join(fbsDir, "backend.fbs");
  writeFileSync(fbsPath, emitFbs(model));

  // 2. + 3. flatc (ts + rust)
  for (const lang of ["ts", "rust"] as const) {
    const outDir = join(ROOT, "src", "generated", lang);
    rmSync(outDir, { recursive: true, force: true });
    mkdirSync(outDir, { recursive: true });
    const args =
      lang === "ts"
        ? ["--ts", "--gen-object-api", "-o", outDir, fbsPath]
        : ["--rust", "-o", outDir, fbsPath];
    run("flatc", args, fbsDir);
  }

  // copy flatc rust output into the crate (flatc emits a single <schema>_generated.rs)
  const rustGenDir = join(ROOT, "src", "generated", "rust");
  const rsFiles = readdirSync(rustGenDir).filter((f) => f.endsWith(".rs"));
  if (rsFiles.length !== 1) {
    throw new Error(`expected exactly one .rs from flatc --rust, got: [${rsFiles.join(", ")}]`);
  }
  const crateGenDir = join(ROOT, "rust", "src", "generated");
  mkdirSync(crateGenDir, { recursive: true });
  copyFileSync(join(rustGenDir, rsFiles[0]!), join(crateGenDir, "backend.rs"));
  writeFileSync(join(crateGenDir, "mod.rs"), "// @generated by scripts/generate.ts — DO NOT EDIT\npub mod backend;\n");

  // 4. Rust JSON→FlatBuffer glue
  const transcodeDir = join(ROOT, "rust", "src", "transcode");
  mkdirSync(transcodeDir, { recursive: true });
  writeFileSync(join(transcodeDir, "generated.rs"), emitRustGlue(model));
  writeFileSync(join(transcodeDir, "mod.rs"), "// @generated by scripts/generate.ts — DO NOT EDIT\npub mod generated;\n");

  // 5. registry (server + client) + direct fast-path serde + browser JS encoder
  writeFileSync(join(ROOT, "src", "generated", "registry.ts"), emitRegistry(model));
  writeFileSync(join(ROOT, "src", "generated", "direct-ser.ts"), emitDirectSer(model));
  writeFileSync(join(ROOT, "src", "generated", "ts-ser.ts"), emitTsSer(model));

  // 6. machine-readable event-id registry for external consumers (NATS bridge,
  //    independent clients). Same FNV-1a ids as the generated registry.
  const wireRegistry = {
    version: WIRE_VERSION,
    events: Object.fromEntries(model.events.map((ev) => [ev.name, eventId(ev.name)])),
  };
  writeFileSync(
    join(ROOT, "src", "generated", "wire-registry.json"),
    JSON.stringify(wireRegistry, null, 2) + "\n",
  );

  console.log(`generated ✓  (${model.events.length} events, ${model.tables.length} tables, ${model.enums.length} enums)`);
}

main();
