import type { FieldDef, Model } from "./schema-model";
import { toSnake } from "./schema-model";

/**
 * Emits `src/generated/ts-ser.ts` — the PURE-JS (browser-safe) object → FlatBuffer
 * encoder, built on flatc's generated object API (`.T` classes + `pack()`).
 *
 * This is the OTHER half of bidirectionality: the Rust FFI serializer only
 * exists on the Bun server, so browser clients cannot use it. `ts-ser` gives
 * any JS runtime (browser or Bun) a way to encode EVERY event — including the
 * transport control frames (hello/subscribe/ping/...) — into the same wire
 * format `[WIRE_VERSION][event_id:u32][size-prefixed FlatBuffer]`.
 *
 * Key points:
 *   - Reuses a single pooled `flatbuffers.Builder` (`getBuilder()`); each
 *     encode clears it, so `encodeEventFrame` (which copies into a fresh
 *     frame) is the safe public API.
 *   - int64 fields convert `number → BigInt` (the flatc object API uses bigint);
 *   - string enums map to flatc numeric enum values via generated lookups.
 *   - Emits `build<Table>T` helpers for nested tables (table / vector-table).
 */
export function emitTsSer(m: Model): string {
  const needed = new Set<string>();
  const visit = (name: string) => {
    if (needed.has(name)) return;
    needed.add(name);
    const t = m.tables.find((t) => t.name === name)!;
    for (const f of t.fields) {
      if (f.kind === "table" || f.kind === "vector-table") visit(f.tableName!);
    }
  };
  for (const ev of m.events) visit(ev.tableName);
  const neededTables = m.tables.filter((t) => needed.has(t.name));

  // enums actually used by a needed table
  const usedEnums = new Map<string, string[]>();
  for (const t of neededTables) {
    for (const f of t.fields) {
      if (f.kind === "enum" || f.kind === "vector-enum") {
        const e = m.enums.find((e) => e.name === f.enumName!);
        if (e) usedEnums.set(e.name, e.values);
      }
    }
  }

  const lines: string[] = [];
  lines.push("// @generated by scripts/ts-ser-gen.ts — DO NOT EDIT");
  lines.push('import * as flatbuffers from "flatbuffers";');
  lines.push("import {");
  for (const t of neededTables) lines.push(`  ${t.name}T,`);
  lines.push('} from "./ts/backend";');
  lines.push('import { anyEventNameToId, WIRE_HEADER_LEN, WIRE_VERSION } from "./registry";');
  lines.push('import type { AnyEventName, ControlEvents, Events } from "../schema";');
  lines.push("");
  lines.push("/** string → flatc numeric enum value lookups */");
  for (const [name, values] of usedEnums) {
    const entries = values.map((v) => `${v}: ${values.indexOf(v)}`).join(", ");
    lines.push(`const ${toSnake(name).toUpperCase()} = { ${entries} } as const;`);
  }
  if (usedEnums.size > 0) lines.push("");
  lines.push("/** pooled builder — each encode clears it (safe because encodeEventFrame copies). */");
  lines.push("let shared: flatbuffers.Builder | null = null;");
  lines.push("function getBuilder(): flatbuffers.Builder {");
  lines.push("  if (!shared) shared = new flatbuffers.Builder(1024);");
  lines.push("  return shared;");
  lines.push("}");
  lines.push("");

  // per-table plain input types
  for (const t of neededTables) {
    lines.push(`type ${t.name}Plain = {`);
    for (const f of t.fields) lines.push(`  ${f.jsonName}${f.required ? "" : "?"}: ${plainType(m, f)};`);
    lines.push("};");
    lines.push("");
  }

  // per-table builders (plain object → flatc .T)
  for (const t of neededTables) {
    lines.push(`function build${t.name}T(o: ${t.name}Plain): ${t.name}T {`);
    lines.push("  return new " + t.name + "T(");
    for (const f of t.fields) lines.push(`    ${ctorArg(f, "o")},`);
    lines.push("  );");
    lines.push("}");
    lines.push("");
  }

  // per-event payload encoders (size-prefixed flatbuffer only)
  for (const ev of m.events) {
    const annot = ev.control
      ? `ControlEvents[${JSON.stringify(ev.name)}]`
      : `Events[${JSON.stringify(ev.name)}]`;
    lines.push(`/** ${ev.control ? "control " : ""}payload encoder: plain object → size-prefixed FlatBuffer. */`);
    lines.push(`export function encode${pascal(ev.name)}Payload(o: ${annot}, b: flatbuffers.Builder = getBuilder()): Uint8Array {`);
    lines.push("  b.clear();");
    lines.push(`  b.finishSizePrefixed(build${ev.tableName}T(o).pack(b));`);
    lines.push("  return b.asUint8Array();");
    lines.push("}");
    lines.push("");
  }

  lines.push("export type JsEncoder = (o: unknown, b?: flatbuffers.Builder) => Uint8Array;");
  lines.push("");
  lines.push("export const jsEncoders: Record<string, JsEncoder> = {");
  for (const ev of m.events) lines.push(`  ${ev.name}: encode${pascal(ev.name)}Payload as JsEncoder,`);
  lines.push("};");
  lines.push("");
  lines.push("/** Encode a payload (app or control event) → size-prefixed FlatBuffer. */");
  lines.push("export function encodeJsPayload(name: AnyEventName, o: unknown, b?: flatbuffers.Builder): Uint8Array {");
  lines.push("  const enc = jsEncoders[name];");
  lines.push('  if (!enc) throw new Error(`ignex: no JS encoder for "${name}" — regenerate`);');
  lines.push("  return enc(o, b);");
  lines.push("}");
  lines.push("");
  lines.push("/** Encode a payload into a full wire frame `[version][event_id:u32][size-prefixed FB]`. */");
  lines.push("export function encodeEventFrame(name: AnyEventName, o: unknown, b?: flatbuffers.Builder): Uint8Array {");
  lines.push("  const payload = encodeJsPayload(name, o, b);");
  lines.push("  const id = anyEventNameToId[name]!;");
  lines.push("  const frame = new Uint8Array(WIRE_HEADER_LEN + payload.byteLength);");
  lines.push("  frame[0] = WIRE_VERSION;");
  lines.push("  new DataView(frame.buffer).setUint32(1, id, true);");
  lines.push("  frame.set(payload, WIRE_HEADER_LEN);");
  lines.push("  return frame;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function plainType(m: Model, f: FieldDef): string {
  switch (f.kind) {
    case "string":
      return f.required ? "string" : "string | undefined";
    case "double":
      return "number";
    case "int64":
      return f.bigint ? "bigint" : "number";
    case "bool":
      return "boolean";
    case "enum":
      return enumUnion(m, f);
    case "table":
      return f.required ? `${f.tableName}Plain` : `${f.tableName}Plain | undefined`;
    case "vector-string":
      return `string[]${f.required ? "" : " | undefined"}`;
    case "vector-double":
      return `number[]${f.required ? "" : " | undefined"}`;
    case "vector-int64":
      return `number[]${f.required ? "" : " | undefined"}`;
    case "vector-bool":
      return `boolean[]${f.required ? "" : " | undefined"}`;
    case "vector-enum":
      return `(${enumUnion(m, f)})[]${f.required ? "" : " | undefined"}`;
    case "vector-table":
      return `${f.tableName}Plain[]${f.required ? "" : " | undefined"}`;
    default:
      return "unknown";
  }
}

/** string literal union of the enum values, e.g. `"buy" | "sell"`. */
function enumUnion(m: Model, f: FieldDef): string {
  const values = m.enums.find((e) => e.name === f.enumName)?.values ?? [];
  return values.map((v) => JSON.stringify(v)).join(" | ");
}

function ctorArg(f: FieldDef, o: string): string {
  const j = `${o}.${f.jsonName}`;
  switch (f.kind) {
    case "string":
      // flatc .T strings are nullable; absent optional → null
      return f.required ? j : `${j} ?? null`;
    case "double":
      return j;
    case "int64":
      // bigint-annotated fields are already bigint (pass through); plain int64
      // are `number` in the Events type → BigInt for the flatc object API
      return f.bigint ? j : `${j} === undefined ? 0n : BigInt(${j})`;
    case "bool":
      return j;
    case "enum":
      return `${toSnake(f.enumName!).toUpperCase()}[${j}]`;
    case "table":
      return f.required ? `build${f.tableName}T(${j})` : `${j} ? build${f.tableName}T(${j}) : null`;
    case "vector-string":
    case "vector-double":
    case "vector-bool":
      return `(${j} ?? [])`;
    case "vector-int64":
      return `(${j} ?? []).map((v) => BigInt(v))`;
    case "vector-enum":
      return `(${j} ?? []).map((v) => ${toSnake(f.enumName!).toUpperCase()}[v])`;
    case "vector-table":
      return `(${j} ?? []).map((v) => build${f.tableName}T(v))`;
    default:
      return j;
  }
}

function pascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
