import type { FieldDef, Model } from "./schema-model";

function fbTypeOf(f: FieldDef): string {
  switch (f.kind) {
    case "string":
      return "string";
    case "double":
      return "double";
    case "int64":
      return "int64";
    case "bool":
      return "bool";
    case "enum":
      return f.enumName!;
    case "table":
      return f.tableName!;
    case "vector-string":
      return "[string]";
    case "vector-double":
      return "[double]";
    case "vector-int64":
      return "[int64]";
    case "vector-bool":
      return "[bool]";
    case "vector-enum":
      return `[${f.enumName}]`;
    case "vector-table":
      return `[${f.tableName}]`;
  }
}

/**
 * TypeBox model → FlatBuffers schema (.fbs). No namespace is used so both
 * `flatc --ts` and `flatc --rust` emit flat, predictable modules. Each event
 * table is its own root (finished size-prefixed on the Rust side, read with
 * `getSizePrefixedRootAsXxx` on the TS side).
 */
export function emitFbs(m: Model): string {
  const lines: string[] = [];
  lines.push("// @generated by scripts/typebox-to-fbs.ts — DO NOT EDIT");
  lines.push("// FlatBuffers schema derived from the TypeBox events registry (schema/index.ts).");
  lines.push("");
  lines.push('file_identifier "IGNX";');
  lines.push("");
  for (const e of m.enums) {
    lines.push(`enum ${e.name} : int32 {`);
    e.values.forEach((v, i) => lines.push(`  ${v.toUpperCase()} = ${i},`));
    lines.push("}");
    lines.push("");
  }
  for (const t of m.tables) {
    lines.push(`table ${t.name} {`);
    for (const f of t.fields) {
      lines.push(`  ${f.fbName}:${fbTypeOf(f)};`);
    }
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}
